[misc]
disable = [
    "firmware",
    "toolbx",
    "containers",
    "gnome_shell_extensions",
    "github_cli_extensions",
]

[post_commands]
"AMD firmware workaround" = "sudo sh -c '[[ -d /root/linux-firmware ]] && sudo cp -rf /root/linux-firmware/amd{,gpu,-ucode} /lib/firmware/' && echo 'Done' || echo 'No workaround needed'"

[git]
repos = ["~/dotfiles"]

[deno]
version = "canary"
